#!/bin/bash
#PBS -P Entropy
#PBS -q parallel
#PBS -l select=1:ncpus=12:mem=64gb
#PBS -l walltime=240:00:00
#PBS -j oe
#PBS -N EntropySweep

cd "${PBS_O_WORKDIR}" || exit 1
export MALLOC_ARENA_MAX=12
export OMP_NUM_THREADS=12
export OPENBLAS_NUM_THREADS=12
export MKL_NUM_THREADS=12
export NUMEXPR_NUM_THREADS=12
source /app1/ebenv Python-3.10.4 || exit 1
unset PYTHONPATH
source "${HOME}/myenv/bin/activate" || exit 1
export MOSEKLM_LICENSE_FILE="${HOME}/mosek/mosek.lic"
"${HOME}/myenv/bin/python3" run_cluster.py 
exit $?
